// Pre-match briefings generated by scripts/briefs.mjs (GH Actions cron) and
// committed to the repo — static import, refreshed on each deploy.
import briefsFile from "../data/briefs.json";

export type Brief = {
  text: string;
  sources: { headline: string; href: string }[];
};

type BriefsFile = {
  generated: string | null;
  briefs: Record<string, Brief>;
};

const FILE = briefsFile as unknown as BriefsFile;
const MAX_AGE_H = 24; // stale briefs are worse than none

export function briefFor(homeKey: string, awayKey: string): Brief | undefined {
  if (!FILE.generated) return undefined;
  const age = Date.now() - Date.parse(FILE.generated);
  if (Number.isNaN(age) || age > MAX_AGE_H * 3600e3) return undefined;
  return FILE.briefs[[homeKey, awayKey].sort().join("|")];
}
