// Compute our OWN team strength ratings with an Elo engine, from raw
// international match results (facts). Output baked into lib/derivedRatings.ts.
//
// World-Football-Elo style: home advantage, goal-difference multiplier, and a
// match-importance weight (World Cup > continental > qualifier > friendly).

import { writeFileSync } from "node:fs";

const CSV =
  "https://raw.githubusercontent.com/martj42/international_results/master/results.csv";

// CSV team name -> our internal key (only the 32 we care about need mapping,
// but Elo runs over ALL teams so ratings are properly contextualised).
const NAME_TO_KEY = {
  "South Africa": "RSA",
  Canada: "CAN",
  Brazil: "BRA",
  Japan: "JPN",
  Germany: "GER",
  Paraguay: "PAR",
  Netherlands: "NED",
  Morocco: "MAR",
  "Ivory Coast": "IVO",
  Norway: "NOR",
  France: "FRA",
  Sweden: "SWE",
  Mexico: "MEX",
  Ecuador: "ECU",
  England: "ENG",
  "DR Congo": "COD",
  Belgium: "BEL",
  Senegal: "SEN",
  "United States": "USA",
  "Bosnia and Herzegovina": "BIH",
  Spain: "ESP",
  Austria: "AUT",
  Portugal: "POR",
  Croatia: "CRO",
  Switzerland: "SUI",
  Algeria: "ALG",
  Australia: "AUS",
  Egypt: "EGY",
  Argentina: "ARG",
  "Cape Verde": "CPV",
  Colombia: "COL",
  Ghana: "GHA",
};

function weight(tournament) {
  const t = tournament.toLowerCase();
  if (t.includes("world cup") && !t.includes("qual")) return 60;
  if (/(copa am|euro|african cup|asian cup|gold cup|confederations)/.test(t))
    return 50;
  if (t.includes("qual") || t.includes("nations league")) return 40;
  if (t.includes("friendly")) return 20;
  return 30;
}

function parseCSV(text) {
  // simple parser; fields have no embedded commas in this dataset
  const lines = text.trim().split("\n");
  lines.shift(); // header
  return lines.map((l) => {
    const [date, home, away, hs, as, tournament, , , neutral] = l.split(",");
    return { date, home, away, hs, as, tournament, neutral };
  });
}

const ratings = new Map(); // team name -> elo
const get = (t) => ratings.get(t) ?? 1500;

function update(m) {
  if (m.hs === "NA" || m.as === "NA" || m.hs === "" || m.as === undefined)
    return;
  const hs = Number(m.hs);
  const as = Number(m.as);
  if (Number.isNaN(hs) || Number.isNaN(as)) return;

  const neutral = m.neutral === "TRUE";
  const hfa = neutral ? 0 : 100;
  const Ra = get(m.home);
  const Rb = get(m.away);
  const dr = Ra + hfa - Rb;
  const We = 1 / (1 + Math.pow(10, -dr / 400));
  const W = hs > as ? 1 : hs === as ? 0.5 : 0;

  const gd = Math.abs(hs - as);
  const G = gd <= 1 ? 1 : gd === 2 ? 1.5 : (11 + gd) / 8;

  const K = weight(m.tournament);
  const delta = K * G * (W - We);
  ratings.set(m.home, Ra + delta);
  ratings.set(m.away, Rb - delta);
}

const res = await fetch(CSV);
const matches = parseCSV(await res.text());
let used = 0;
for (const m of matches) {
  const before = ratings.size;
  update(m);
  if (ratings.size >= before) used++;
}

// pull our 32
const derived = {};
const missing = [];
for (const [name, key] of Object.entries(NAME_TO_KEY)) {
  if (ratings.has(name)) derived[key] = Math.round(ratings.get(name));
  else missing.push(name);
}

// reporting
const top = [...ratings.entries()].sort((a, b) => b[1] - a[1]).slice(0, 20);
console.log("=== TOP 20 (our Elo) ===");
top.forEach(([n, r], i) => console.log(String(i + 1).padStart(2), n.padEnd(22), Math.round(r)));
console.log("=== OUR 32 ===");
Object.entries(derived)
  .sort((a, b) => b[1] - a[1])
  .forEach(([k, r]) => console.log(k.padEnd(4), r));
if (missing.length) console.log("!!! UNMATCHED NAMES:", missing);

// write TS
const body =
  "// AUTO-GENERATED by scripts/compute-ratings.mjs — our own Elo from raw\n" +
  "// international results (martj42/international_results). Re-run to refresh.\n\n" +
  "export const DERIVED_RATINGS: Record<string, number> = " +
  JSON.stringify(derived, null, 2) +
  ";\n";
writeFileSync(new URL("../lib/derivedRatings.ts", import.meta.url), body);
console.log("\nwrote lib/derivedRatings.ts");
